name: condaenv
channels:
  - conda-forge

dependencies:
  - python=3.10

  # Paket ML / CV via conda
  - numpy
  - opencv
  - face-recognition

  # Paket Web & Lainnya
  - fastapi
  - uvicorn
  - requests

  # Paket pip dari PyPI
  - pip:
      # - face-recognition==1.3.0 --no-deps
      # - face_recognition_models==0.3.0
      - mediapipe==0.10.21
      - gmqtt
      - supabase
      - python-dotenv
      - paddlepaddle
      - paddleocr
